#THIS CODE WILL CALL DATASET GENERATED BY “population dynamics code.R”：CountData_C_extd


library(here)
library(readxl)
library(nls2)
library(ggplot2)
library(patchwork)
library(dplyr)
library(Metrics) 
library(yardstick)
library(tidyverse)
library(patchwork)
library(forcats)

setwd(here())


#plot the correlation between size of individuals from different stage groups with size of stage groups
#############################################################################
#load the indiviudal size data
SizeData=read_xlsx("Data/MQ test_ Count and Size data.xlsx", sheet = "SizeData")
# get the data for control
SizeData_C<-subset(SizeData,treatment=="C")

#-------------------------------------------------------------------------------
#Standardize the body size within each stage group to [0,1]
# List of stage columns to be standardized
stage_size_columns <- c(
  "F", "FM", "SM", 
  "tritos", "protos", "larvae", "eggs", 
  "Qtritos", "Qprotos", "Qlarvae", 
  "deutos", "Qdeutos"
)

# Apply min-max scaling (0–1) to each stage column
SizeData_C_scaled <- SizeData_C %>%
  mutate(across(
    all_of(stage_size_columns),
    ~ (. - min(., na.rm = TRUE)) / (max(., na.rm = TRUE) - min(., na.rm = TRUE)),
    .names = "{.col}"
  ))

#-------------------------------------------------------------------------------
#merge countdata and size data
merged_data <- left_join(SizeData_C_scaled, CountData_C_extd, by = c("day", "tube"))

#analyze the size and abundance relationship
# List of relevant stages and their corresponding abundance columns
stages <- c("F", "FM", "SM", "tritos","protos","larvae","eggs", "Qtritos", 
            "Qprotos", "Qlarvae","deutos", "Qdeutos")
abundance_cols <- c("noeggs", "nojuveniles","nototal")

# Function to create one plot per stage
plot_list <- map2(
  .x = stages,
  .y = abundance_cols,
  .f = function(stage, abundance) {
    
    # Filter out missing values
    df <- merged_data %>%
      filter(!is.na(.data[[stage]]), !is.na(.data[[abundance]]))
    
    # Create ggplot
    ggplot(df, aes(x = .data[[abundance]], y = .data[[stage]])) +
      geom_point(alpha = 0.4, color = "steelblue") +
      geom_smooth(method = "lm", se = TRUE, color = "darkred") +
      labs(
        title = paste("Stage:", str_to_title(stage)),
        x = paste("Abundance of", abundance),
        y = paste("Scaled size of", stage)
      ) +
      theme_minimal()
  }
)

# Combine plots (adjust layout as needed)
combined_plot <- wrap_plots(plot_list, ncol = 2)

# Save or display
ggsave("Results/size_vs_abundance.png", combined_plot, width = 10, height = 8, dpi = 300)
print(combined_plot)



panel.cor <- function(x, y, digits = 2, prefix = "", cex.cor, ...) {
  usr <- par("usr")
  on.exit(par(usr))
  par(usr = c(0, 1, 0, 1))
  Cor <- cor(x, y, use="pairwise.complete.obs") # Remove abs function if desired
  txt <- paste0(prefix, format(c(Cor, 0.123456789), digits = digits)[1])
  if(missing(cex.cor)) {
    cex.cor <- 0.4 / strwidth(txt)
  }
  text(0.5, 0.5, txt,
       cex = 1 + cex.cor * abs(Cor)) # Resize the text by level of correlation
}

merged_data_Preequ<-subset(merged_data, merged_data$Equ=="Pre-equ")
merged_data_Postequ<-subset(merged_data,merged_data$Equ=="Post-equ")

al <-merged_data[, c(9:20, 42, 43, 44, 41)] 
al <-merged_data_Preequ[, c(9:15, 42, 43, 44, 41)] 
al <-merged_data_Postequ[, c(9:20, 42, 43, 44, 41)] 

pairs(al,
      #col=merged_data$tube, 
      upper.panel = panel.cor,    # Correlation panel
      lower.panel = panel.smooth, na.rm=T) # Smoothed regression lines)


al <-merged_data[, c(42,9)]  #F vs noadults
pairs(al,
      #col=merged_data$trend, 
      col=merged_data$Equ, 
      #col=merged_data$tube, 
      upper.panel = panel.cor,    # Correlation panel
      lower.panel = panel.smooth, na.rm=T) # Smoothed regression lines)



al_log <- data.frame(noadults = log(al$noadults), F = log(al$F))
pairs(
  al_log,
  col=merged_data$Equ, 
  #col=merged_data$Equ, 
  #col=merged_data$tube, 
  upper.panel = panel.cor,
  # Correlation panel
  lower.panel = panel.smooth,
  na.rm = T
) # Smoothed regression lines)


############################################################################3

# relationshiop at specific tube
#############################################################################
#Tube 3
merged_data_T3<-subset(merged_data,tube==3)
al <-merged_data_T3[, c(9:20, 42, 43, 44, 41,46)] 

al<-merged_data_T3[, c(42, 9)]  #F vs noadults
al<-merged_data_T3[, c(42, 10)] # FM vs noadults
al<-merged_data_T3[, c(42, 11)] # SM vs noaudlts
al<-merged_data_T3[, c(42, 16)] # Qtritos vs noaudlts
al<-merged_data_T3[, c(42, 17)] # Qprotos vs noaudlts
al<-merged_data_T3[, c(42, 19)] # deutos vs noaudlts

#select one al from above
pairs(al,
      col=merged_data_T3$Equ, 
      upper.panel = panel.cor,    # Correlation panel
      lower.panel = panel.smooth, na.rm=T) # Smoothed regression lines)


#Tube 5
merged_data_T5<-subset(merged_data,tube==5)
al <-merged_data_T5[, c(9:20, 42, 43, 44, 41)] 
# Remove columns that are completely NA
al <- al[, colSums(is.na(al)) < nrow(al)] 

al<-merged_data_T5[, c(42, 9)]  #F vs noadults
al<-merged_data_T5[, c(42, 10)] # FM vs noadults
al<-merged_data_T5[, c(42, 11)] # SM vs noaudlts
al<-merged_data_T5[, c(42, 16)] # Qtritos vs noaudlts
al<-merged_data_T5[, c(42, 17)] # Qprotos vs noaudlts
al<-merged_data_T5[, c(42, 19)] # deutos vs noaudlts

#select one al from above
pairs(al,
      col=merged_data_T5$Equ, 
      upper.panel = panel.cor,    # Correlation panel
      lower.panel = panel.smooth, na.rm=T) # Smoothed regression lines)

#Tube 8
merged_data_T8<-subset(merged_data,tube==8)
al <-merged_data_T8[, c(9:20, 42, 43, 44, 41)] 
al<-merged_data_T8[, c(42, 9)]  #F vs noadults
al<-merged_data_T8[, c(42, 10)] # FM vs noadults
al<-merged_data_T8[, c(42, 11)] # SM vs noaudlts
al<-merged_data_T8[, c(42, 16)] # Qtritos vs noaudlts
al<-merged_data_T8[, c(42, 17)] # Qprotos vs noaudlts
al<-merged_data_T8[, c(42, 19)] # deutos vs noaudlts

#select one al from above
pairs(al,
      col=merged_data_T8$Equ, 
      upper.panel = panel.cor,    # Correlation panel
      lower.panel = panel.smooth, na.rm=T) # Smoothed regression lines)

################################################################################

# Calculate mean and standard deviation for each combination of day and noadults
################################################################################
#For F vs noadults with st-dev as legend
#--------------------------------------------------------------------------------
#for tube 3,5, 8,  change merged_data_T3, to ..._5, ..._8 
al<-merged_data_T8[, c(4, 42, 9)]  #F vs noadults
summary_al <- al %>%
  group_by(day, noadults) %>%
  summarize(
    mean_F = ifelse(all(is.na(F)), NA, mean(F, na.rm = TRUE)),  # Mean of F
    sd_F = ifelse(all(is.na(F)), NA, sd(F, na.rm = TRUE))       # Standard deviation of F
  )

# Load the ggplot2 package
library(ggplot2)
# Scatter plot with custom axis and color scales
ggplot(summary_al, aes(x = noadults, y = mean_F, color = sd_F)) +
  geom_point(size = 3) +  # Scatter plot points
  geom_smooth(method = "loess", se = FALSE, color = "black") +  # Smooth trend line (loess)
  
  # Customizing the x-axis scale (setting limits and breaks)
  scale_x_continuous(
    name = "Number of Adults (noadults)",  # Custom x-axis label
    limits = c(0, 80),  # Set limits from 0 to 20
    breaks = seq(0, 80, by = 10)  # Breaks every 5 units
  ) +
  
  # Customizing the y-axis scale (setting limits and breaks)
  scale_y_continuous(
    name = "Mean of F (mean_F)",  # Custom y-axis label
    limits = c(500, 900),  # Set limits from 0 to 100
    breaks = seq(500, 900, by = 100)  # Breaks every 20 units
  ) +
  
  # Customizing the color legend (scale for sd_F)
  scale_color_gradient(
    low = "blue", high = "red",  # Color gradient from blue to red
    limits = c(0, 200),  # Set limits for sd_F from 0 to 30
    breaks = seq(0, 200, by = 20),  # Breaks for the legend at intervals of 10
    name = "Standard Deviation (sd_F)"  # Legend title
  ) +
  
  labs(title = "Scatter Plot of mean_F vs noadults with Custom Scales") +
  theme_minimal()
#-----------------------------------------------------------------------------
##For F vs noadults with equalibrium status color coded
#-----------------------------------------------------------------------------
#for tube 3,5, 8,  change merged_data_T3, to ..._5, ..._8 
al<-merged_data_T8[, c(4, 42,46,9)]  #F vs noadults
summary_al <- al %>%
  group_by(day, noadults, Equ) %>%
  summarize(
    mean_F = ifelse(all(is.na(F)), NA, mean(F, na.rm = TRUE)),  # Mean of F
    sd_F = ifelse(all(is.na(F)), NA, sd(F, na.rm = TRUE))       # Standard deviation of F
  )

# Load the ggplot2 package
library(ggplot2)
# Scatter plot with custom axis and color scales
ggplot(summary_al, aes(x = noadults, y = mean_F, color = Equ)) +
  geom_point(size = 3) +  # Scatter plot points
  geom_smooth(method = "loess", se = FALSE, color = "black") +  # Smooth trend line (loess)+
  labs(title = "Scatter Plot of mean_F vs noadults with Custom Scales") +
  theme_minimal()
##-------------------------------------------------------------------------------
#For F vs nototal with st-dev as legend
#--------------------------------------------------------------------------------
#for tube 3,5, 8,  change merged_data_T3, to ..._5, ..._8 
al<-merged_data_T3[, c(4, 41, 9)]  #F vs noadults
summary_al <- al %>%
  group_by(day, nototal) %>%
  summarize(
    mean_F = ifelse(all(is.na(F)), NA, mean(F, na.rm = TRUE)),  # Mean of F
    sd_F = ifelse(all(is.na(F)), NA, sd(F, na.rm = TRUE))       # Standard deviation of F
  )

# Load the ggplot2 package
library(ggplot2)
# Scatter plot with custom axis and color scales
ggplot(summary_al, aes(x = nototal, y = mean_F, color = sd_F)) +
  geom_point(size = 3) +  # Scatter plot points
  geom_smooth(method = "loess", se = FALSE, color = "black") +  # Smooth trend line (loess)
  
  # Customizing the x-axis scale (setting limits and breaks)
  scale_x_continuous(
    name = "Population size (nototal)",  # Custom x-axis label
    limits = c(0, 600),  # Set limits from 0 to 20
    breaks = seq(0, 600, by = 100)  # Breaks every 5 units
  ) +
  
  # Customizing the y-axis scale (setting limits and breaks)
  scale_y_continuous(
    name = "Mean of F (mean_F)",  # Custom y-axis label
    limits = c(500, 900),  # Set limits from 0 to 100
    breaks = seq(500, 900, by = 100)  # Breaks every 20 units
  ) +
  
  # Customizing the color legend (scale for sd_F)
  scale_color_gradient(
    low = "blue", high = "red",  # Color gradient from blue to red
    limits = c(0, 200),  # Set limits for sd_F from 0 to 30
    breaks = seq(0, 200, by = 20),  # Breaks for the legend at intervals of 10
    name = "Standard Deviation (sd_F)"  # Legend title
  ) +
  
  labs(title = "Scatter Plot of mean_F vs nototal with Custom Scales") +
  theme_minimal()
#-----------------------------------------------------------------------------
##For F vs nototal with equalibrium status color coded
#-----------------------------------------------------------------------------
#for tube 3,5, 8,  change merged_data_T3, to ..._5, ..._8 
al<-merged_data_T3[, c(4, 41,46,9)]  #F vs noadults
summary_al <- al %>%
  group_by(day, nototal, Equ) %>%
  summarize(
    mean_F = ifelse(all(is.na(F)), NA, mean(F, na.rm = TRUE)),  # Mean of F
    sd_F = ifelse(all(is.na(F)), NA, sd(F, na.rm = TRUE))       # Standard deviation of F
  )

# Load the ggplot2 package
library(ggplot2)
# Scatter plot with custom axis and color scales
ggplot(summary_al, aes(x = nototal, y = mean_F, color = Equ)) +
  geom_point(size = 3) +  # Scatter plot points
  geom_smooth(method = "loess", se = FALSE, color = "black") +  # Smooth trend line (loess)+
  labs(title = "Scatter Plot of mean_F vs nototal with Custom Scales") +
  theme_minimal()
##-------------------------------------------------------------------------------

al<-merged_data_T8[, c(4, 42,46,9)]  #F vs noadults
summary_al <- al %>%
  group_by(day, noadults, Equ) %>%
  summarize(
    mean_F = ifelse(all(is.na(F)), NA, mean(F, na.rm = TRUE)),  # Mean of F
    sd_F = ifelse(all(is.na(F)), NA, sd(F, na.rm = TRUE))       # Standard deviation of F
  )

# Load the ggplot2 package
library(ggplot2)
# Scatter plot with custom axis and color scales
ggplot(summary_al, aes(x = noadults, y = mean_F, color = Equ)) +
  geom_point(size = 3) +  # Scatter plot points
  geom_smooth(method = "loess", se = FALSE, color = "black") +  # Smooth trend line (loess)+
  
  
  labs(title = "Scatter Plot of mean_F vs noadults with Custom Scales") +
  theme_minimal()

#--------------------------------------------------------------------------

#For FM
#for tube 3,5, 8,  change merged_data_T3, to ..._5, ..._8 
al<-merged_data_T3[, c(4, 42, 10)]  #FM vs noadults
summary_al <- al %>%
  group_by(day, noadults) %>%
  summarize(
    mean_FM = ifelse(all(is.na(FM)), NA, mean(FM, na.rm = TRUE)),  # Mean of FM
    sd_FM = ifelse(all(is.na(FM)), NA, sd(FM, na.rm = TRUE))       # Standard deviation of FM
  )

# Load the ggplot2 package
library(ggplot2)
# Scatter plot with custom axis and color scales
ggplot(summary_al, aes(x = noadults, y = mean_FM, color = sd_FM)) +
  geom_point(size = 3) +  # Scatter plot points
  geom_smooth(method = "loess", se = FALSE, color = "black") +  # Smooth trend line (loess)
  
  # Customizing the x-axis scale (setting limits and breaks)
  scale_x_continuous(
    name = "Number of Adults (noadults)",  # Custom x-axis label
    limits = c(0, 80),  # Set limits from 0 to 20
    breaks = seq(0, 80, by = 10)  # Breaks every 5 units
  ) +
  
  # Customizing the y-axis scale (setting limits and breaks)
  scale_y_continuous(
    name = "Mean of FM (mean_FM)",  # Custom y-axis label
    limits = c(500, 900),  # Set limits from 0 to 100
    breaks = seq(500, 900, by = 100)  # Breaks every 20 units
  ) +
  
  # Customizing the color legend (scale for sd_FM)
  scale_color_gradient(
    low = "blue", high = "red",  # Color gradient from blue to red
    limits = c(0, 200),  # Set limits for sd_FM from 0 to 30
    breaks = seq(0, 200, by = 20),  # Breaks for the legend at intervals of 10
    name = "Standard Deviation (sd_FM)"  # Legend title
  ) +
  
  labs(title = "Scatter Plot of mean_FM vs noadults with Custom Scales") +
  theme_minimal()


###############################################################################
#statistical test with raw readings
StaTest<-merged_data[,c(4,8,9,42,41,45,46)] 

# Load lme4 package
library(lme4)
#------------------------------------------------------------------------------
# F vs noadults
#------------------------------------------------------------------------------
# Fit a mixed-effects model with tube as random effects, day as fixed
model21 <- lmer(F ~ noadults + day + (1 | tube) , data=StaTest)
model22 <- lmer(F ~ noadults + noadults^2 + day  + (1 | tube) , data=StaTest) 
model23 <- lmer(F ~ noadults + noadults^2 + noadults^3 +day  + (1 | tube) , data=StaTest) 
# Fit a mixed-effects model with tube as random effects, day as fixed, equ as fixed
model31 <- lmer(F ~ noadults + day +Equ + (1 | tube) , data=StaTest) 
model32 <- lmer(F ~ noadults + noadults^2 + day +Equ + (1 | tube) , data=StaTest) 
model33 <- lmer(F ~ noadults + noadults^2 + noadults^3 + day +Equ + (1 | tube) , data=StaTest) 
# Fit a mixed-effects model with tube as random effects, day as random, equ as fixed
model41 <- lmer(F ~ noadults  +Equ + (1 | tube) + (1|day), data=StaTest) 
model42 <- lmer(F ~ noadults + noadults^2  +Equ + (1 | tube) + (1|day), data=StaTest) 
model43 <- lmer(F ~ noadults + noadults^2 + noadults^3 + Equ + (1 | tube)+ (1|day) , data=StaTest) 
AIC(model21, model22,model23, model31, model32, model33, model41, model42, model43)
#------------------------------------------------------------------------------
# F vs nototal
#------------------------------------------------------------------------------
# Fit a mixed-effects model with tube as random effects, day as fixed
model21 <- lmer(F ~ nototal + day + (1 | tube) , data=StaTest)
model22 <- lmer(F ~ nototal + nototal^2 + day  + (1 | tube) , data=StaTest) 
model23 <- lmer(F ~ nototal + nototal^2 + nototal^3 +day  + (1 | tube) , data=StaTest) 
# Fit a mixed-effects model with tube as random effects, day as fixed, equ as fixed
model31 <- lmer(F ~ nototal + day +Equ + (1 | tube) , data=StaTest) 
model32 <- lmer(F ~ nototal + nototal^2 + day +Equ + (1 | tube) , data=StaTest) 
model33 <- lmer(F ~ nototal + nototal^2 + nototal^3 + day +Equ + (1 | tube) , data=StaTest) 
# Fit a mixed-effects model with tube as random effects, day as random, equ as fixed
model41 <- lmer(F ~ nototal  +Equ + (1 | tube) + (1|day), data=StaTest) 
model42 <- lmer(F ~ nototal + nototal^2  +Equ + (1 | tube) + (1|day), data=StaTest) 
model43 <- lmer(F ~ nototal + nototal^2 + nototal^3 + Equ + (1 | tube)+ (1|day) , data=StaTest) 
AIC(model21, model22,model23, model31, model32, model33, model41, model42, model43)

#------------------------------------------------------------------------------
#mean_F vs noadults
#------------------------------------------------------------------------------
#statistical test with mean body size
summary_StaTest <- StaTest %>%
  group_by(day, tube, Equ, noadults) %>%
  summarize(
    mean_F = ifelse(all(is.na(F)), NA, mean(F, na.rm = TRUE)),  # Mean of F
    sd_F = ifelse(all(is.na(F)), NA, sd(F, na.rm = TRUE))       # Standard deviation of F
  )
library(ggplot2)
# Scatter plot with custom axis and color scales
ggplot(summary_StaTest, aes(x = noadults, y = mean_F, color = Equ)) +
  geom_point(size = 3) +  # Scatter plot points
  geom_smooth(method = "loess", se = FALSE, color = "black") +  # Smooth trend line (loess)+
  labs(title = "Scatter Plot of mean_F vs noadults with Custom Scales") +
  theme_minimal()

ggplot(summary_StaTest, aes(x = noadults, y = mean_F, color = sd_F)) +
  geom_point(size = 3) +  # Scatter plot points
  geom_smooth(method = "loess", se = FALSE, color = "black") +  # Smooth trend line (loess)+
  labs(title = "Scatter Plot of mean_F vs noadults with Custom Scales") +
  theme_minimal()


# Fit a mixed-effects model with tube as random effects, day as fixed
model21 <- lmer(mean_F ~ noadults + day + (1 | tube) , data=summary_StaTest)
model22 <- lmer(mean_F ~ noadults + noadults^2 + day  + (1 | tube) , data=summary_StaTest) 
model23 <- lmer(mean_F ~ noadults + noadults^2 + noadults^3 +day  + (1 | tube) , data=summary_StaTest) 
# Fit a mixed-effects model with tube as random effects, day as fixed, equ as fixed
model31 <- lmer(mean_F ~ noadults + day +Equ + (1 | tube) , data=summary_StaTest) 
model32 <- lmer(mean_F ~ noadults + noadults^2 + day +Equ + (1 | tube) , data=summary_StaTest) 
model33 <- lmer(mean_F ~ noadults + noadults^2 + noadults^3 + day +Equ + (1 | tube) , data=summary_StaTest) 
# Fit a mixed-effects model with tube as random effects, day as random, equ as fixed
model41 <- lmer(mean_F ~ noadults  +Equ + (1 | tube) + (1|day), data=summary_StaTest) 
model42 <- lmer(mean_F ~ noadults + noadults^2  +Equ + (1 | tube) + (1|day), data=summary_StaTest) 
model43 <- lmer(mean_F ~ noadults + noadults^2 + noadults^3 + Equ + (1 | tube)+ (1|day) , data=summary_StaTest) 
AIC(model21, model22,model23, model31, model32, model33, model41, model42, model43)

#-------------------------------------------------------------------------------
#mean_F vs nototal
#------------------------------------------------------------------------------
#statistical test with mean body size
summary_StaTest <- StaTest %>%
  group_by(day, tube, Equ, nototal) %>%
  summarize(
    mean_F = ifelse(all(is.na(F)), NA, mean(F, na.rm = TRUE)),  # Mean of F
    sd_F = ifelse(all(is.na(F)), NA, sd(F, na.rm = TRUE))       # Standard deviation of F
  )
library(ggplot2)
# Scatter plot with custom axis and color scales
ggplot(summary_StaTest, aes(x = nototal, y = mean_F, color = Equ)) +
  geom_point(size = 3) +  # Scatter plot points
  geom_smooth(method = "loess", se = FALSE, color = "black") +  # Smooth trend line (loess)+
  labs(title = "Scatter Plot of mean_F vs nototal with Custom Scales") +
  theme_minimal()

ggplot(summary_StaTest, aes(x = nototal, y = mean_F, color = sd_F)) +
  geom_point(size = 3) +  # Scatter plot points
  geom_smooth(method = "loess", se = FALSE, color = "black") +  # Smooth trend line (loess)+
  labs(title = "Scatter Plot of mean_F vs nototal with Custom Scales") +
  theme_minimal()


# Fit a mixed-effects model with tube as random effects, day as fixed
model21 <- lmer(mean_F ~ nototal + day + (1 | tube) , data=summary_StaTest)
model22 <- lmer(mean_F ~ nototal + nototal^2 + day  + (1 | tube) , data=summary_StaTest) 
model23 <- lmer(mean_F ~ nototal + nototal^2 + nototal^3 +day  + (1 | tube) , data=summary_StaTest) 
# Fit a mixed-effects model with tube as random effects, day as fixed, equ as fixed
model31 <- lmer(mean_F ~ nototal + day +Equ + (1 | tube) , data=summary_StaTest) 
model32 <- lmer(mean_F ~ nototal + nototal^2 + day +Equ + (1 | tube) , data=summary_StaTest) 
model33 <- lmer(mean_F ~ nototal + nototal^2 + nototal^3 + day +Equ + (1 | tube) , data=summary_StaTest) 
# Fit a mixed-effects model with tube as random effects, day as random, equ as fixed
model41 <- lmer(mean_F ~ nototal  +Equ + (1 | tube) + (1|day), data=summary_StaTest) 
model42 <- lmer(mean_F ~ nototal + nototal^2  +Equ + (1 | tube) + (1|day), data=summary_StaTest) 
model43 <- lmer(mean_F ~ nototal + nototal^2 + nototal^3 + Equ + (1 | tube)+ (1|day) , data=summary_StaTest) 
AIC(model21, model22,model23, model31, model32, model33, model41, model42, model43)



# Asssumption check
#STEP1-homoscedasticity check  (Residuals vs Fitted values plot)
#you want to see residuals have constant variance across fitted values (homoscedasticity), i.e. no clear pattern or funnel shape.
library(ggplot2)
# Extract fitted values and residuals
fitted_vals <- fitted(model)
residuals_vals <- resid(model)
# Create a residuals vs fitted plot

ggplot(data = NULL, aes(x = fitted_vals, y = residuals_vals)) +
  geom_point() +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  labs(x = "Fitted Values", y = "Residuals", title = "Residuals vs Fitted") +
  theme_minimal()


#STEP2-Normality of Residuals check (Q-Q Plot)
#  Residuals should ideally fall along the reference line.
ggplot(data = NULL, aes(sample = residuals_vals)) +
  stat_qq() +
  stat_qq_line(color = "red") +
  labs(title = "Q-Q Plot of Residuals") +
  theme_minimal()

# Another Normality check (Histogram of residuals)
ggplot(data = NULL, aes(x = residuals_vals)) +
  geom_histogram(binwidth = 10, fill = "blue", alpha = 0.7, color = "black") +
  labs(x = "Residuals", y = "Count", title = "Histogram of Residuals") +
  theme_minimal()

#STEP3-Check for Influential Observations (Leverage and Cook’s Distance)
# Calculate Cook's distance for influential points
#This will help you identify any points that have undue influence on your model.
cooksd <- cooks.distance(model)
# Plot Cook's distance
plot(cooksd, type = "h", ylab = "Cook's Distance", main = "Cook's Distance Plot")
abline(h = 4/(nrow(StaTest)-length(fixef(model))), col = "red")  # Threshold line for large Cook's distance

#STEP4- Check for Random Effect Independence
# Plot residuals vs random effects
ranef_tube <- model.frame(model)$tube
ranef_day<-model.frame(model)$day
residuals_vals <- resid(model)
REI<-data.frame("ranef_tube"=ranef_tube,
                "ranef_day"=ranef_day,
                "residual_vals"=residuals_vals)
ggplot(data = REI, aes(x = ranef_tube, y = residuals_vals)) +
  geom_point() +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  labs(x = "Random Effects (tube)", y = "Residuals", title = "Residuals vs Random Effects (tube)") +
  theme_minimal()
ggplot(data = REI, aes(x = ranef_day, y = residuals_vals)) +
  geom_point() +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  labs(x = "Random Effects (tube)", y = "Residuals", title = "Residuals vs Random Effects (tube)") +
  theme_minimal()




model <- lmer(body_size ~ population_density + (1 | tube) + (1 | day/tube), data = StaTest)


# Summary of the model
summary(model)
