#THIS CODE WILL CALL DATASET GENERATED BY “population dynamics code.R”：CountData_C_extd

library(here)
library(readxl)
library(nls2)
library(ggplot2)
library(patchwork)
library(dplyr)
library(Metrics) 
library(yardstick)
library(tidyverse)
library(patchwork)
library(forcats)

setwd(here())


#plot the correlation between size of individuals from different stage groups with size of stage groups
#############################################################################
#load the indiviudal size data
SizeData=read_xlsx("Data/MQ test_ Count and Size data.xlsx", sheet = "SizeData")
# get the data for control
SizeData_C_raw<-subset(SizeData,treatment=="C")

#-------------------------------------------------------------------------------
#Standardize the body size within each stage group to [0,1]
# List of stage columns to be standardized
stage_size_columns <- c(
  "F", "FM", "SM", 
  "tritos", "protos", "larvae", "eggs", 
  "Qtritos", "Qprotos", "Qlarvae", 
  "deutos", "Qdeutos"
)

# Copy data to preserve original
SizeData_C <- SizeData_C_raw

# Track total number of outliers
outlier_counts <- numeric(length(stage_size_columns))
names(outlier_counts) <- stage_size_columns

# Step 1: Remove outliers per stage column
for (col in stage_size_columns) {
  vals <- SizeData_C[[col]]
  q1 <- quantile(vals, 0.25, na.rm = TRUE)
  q3 <- quantile(vals, 0.75, na.rm = TRUE)
  iqr <- q3 - q1
  lower <- q1 - 3 * iqr
  upper <- q3 + 3 * iqr
  
  # Identify outliers
  outliers <- which(vals < lower | vals > upper)
  outlier_counts[col] <- length(outliers)
  
  # Replace with NA
  SizeData_C[[col]][outliers] <- NA
}


# Apply min-max scaling (0–1) to each stage column
SizeData_C_scaled <- SizeData_C %>%
  mutate(across(
    all_of(stage_size_columns),
    ~ (. - min(., na.rm = TRUE)) / (max(., na.rm = TRUE) - min(., na.rm = TRUE)),
    .names = "{.col}"
  ))

#-------------------------------------------------------------------------------
#merge countdata and size data
merged_data<- left_join(SizeData_C, CountData_C_extd, by = c("day", "tube"))
merged_data_scaled <- left_join(SizeData_C_scaled, CountData_C_extd, by = c("day", "tube"))

#-------------------------------------------------------------------------------
#analyze the size vs abundance coefficient
# List of relevant stages and their corresponding abundance columns
stages <- c("F", "FM", "SM","Qtritos", "Qprotos", "Qdeutos", "Qlarvae",
            "tritos", "deutos", "protos","larvae","eggs")
abundance_cols <- c("noeggs", "nojuveniles","noadults","nototal", "q")


library("corrplot")
library(psych)

#select the columns of interest for correlation analysis

cor_df <- merged_data_scaled %>%
  select(all_of(c(stages, abundance_cols))) 

# 1) Remove all-NA columns first
cor_df2 <- cor_df %>%
  select(where(~ !all(is.na(.)))) %>%
  select(where(~ sd(., na.rm = TRUE) > 0))

# 2) Correlation matrix
cor_res <- rcorr(as.matrix(cor_df2), type = "spearman")

R <- cor_res$r
P <- cor_res$P

# 3) BH-adjust only the upper triangle p-values
P_adj <- matrix(NA_real_, nrow = nrow(P), ncol = ncol(P),
                dimnames = dimnames(P))

upper_idx <- upper.tri(P, diag = FALSE)
P_adj[upper_idx] <- p.adjust(P[upper_idx], method = "BH")

# mirror to lower triangle
P_adj[lower.tri(P_adj)] <- t(P_adj)[lower.tri(P_adj)]
diag(P_adj) <- 0

#plot the correlation coefficient
tiff("Results/Correlation between Abundance and individual size.tiff", 
     width = 5, height = 5, units = "in", res = 600)

corrplot(
  R,
  method = "circle",
  type = "upper",
  order = "original",
  tl.col = "black",
  tl.srt = 45,
  p.mat = P_adj,
  sig.level = c(0.001,0.01,0.05), #only plot the one that are statistically significant
  insig = "label_sig",
  pch.cex = 0.8,
  #insig = "blank"
)
dev.off()
#-------------------------------------------------------------------------------
#stage specific body size vs relative density (q)
library(dplyr)
library(tidyr)
library(purrr)
library(mgcv)
library(ggplot2)
library(e1071)
library(patchwork)

################################################################################
# 1) Reshape to long format and calculate stage-level summaries
################################################################################

stage_summary <- merged_data_scaled %>%
  select(tube, day, q, all_of(stage_size_columns)) %>%
  pivot_longer(
    cols = all_of(stage_size_columns),
    names_to = "stage",
    values_to = "size"
  ) %>%
  filter(!is.na(size), !is.na(q)) %>%
  group_by(tube, day, q, stage) %>%
  summarise(
    mean_size = mean(size, na.rm = TRUE),
    cv_size   = ifelse(mean(size, na.rm = TRUE) == 0,
                       NA_real_,
                       sd(size, na.rm = TRUE) / mean(size, na.rm = TRUE)),
    skew_size = if (sum(!is.na(size)) >= 3) {
      e1071::skewness(size, type = 2, na.rm = TRUE)
    } else {
      NA_real_
    },
    n = sum(!is.na(size)),
    .groups = "drop"
  ) %>%
  mutate(
    tube  = factor(tube),
    stage = factor(stage, levels = stage_size_columns)
  )
################################################################################
# 2) Fit stage-specific GAMs for each metric
################################################################################

fit_stage_gam <- function(df, response) {
  fml <- as.formula(paste0(response, " ~ s(q, k = 5) + tube"))
  
  gam(
    formula = fml,
    data = df,
    method = "REML"
  )
}



# Split by stage
stage_split <- split(stage_summary, stage_summary$stage)

# Keep only stages with enough data
stage_split <- stage_split[
  sapply(stage_split, function(x) {
    nrow(x) >= 10 &&
      sum(!is.na(x$q)) >= 10 &&
      length(unique(x$q)) > 3
  })
]

# Fit one GAM per stage per metric
stage_gam_list <- lapply(stage_split, function(dat) {
  list(
    Mean = fit_stage_gam(dat, "mean_size"),
    CV   = fit_stage_gam(dat, "cv_size"),
    Skew = fit_stage_gam(dat, "skew_size")
  )
})

################################################################################
# 3) Prediction function
################################################################################

make_pred_df <- function(model, dat, response_name) {
  q_seq <- seq(
    min(dat$q, na.rm = TRUE),
    max(dat$q, na.rm = TRUE),
    length.out = 200
  )
  
  ref_tube <- levels(dat$tube)[1]
  
  newdat <- data.frame(
    q = q_seq,
    tube = factor(ref_tube, levels = levels(dat$tube))
  )
  
  pred <- predict(model, newdata = newdat, se.fit = TRUE)
  
  newdat$fit <- pred$fit
  newdat$lwr <- pred$fit - 1.96 * pred$se.fit
  newdat$upr <- pred$fit + 1.96 * pred$se.fit
  newdat$response <- response_name
  
  newdat
}

################################################################################
# 4) Build prediction data for all stages and metrics
################################################################################

pred_list <- imap_dfr(stage_gam_list, function(mods, st) {
  dat_st <- stage_summary %>% filter(stage == st)
  
  bind_rows(
    make_pred_df(mods$Mean, dat_st, "Mean") %>% mutate(stage = st),
    make_pred_df(mods$CV,   dat_st, "CV")   %>% mutate(stage = st),
    make_pred_df(mods$Skew, dat_st, "Skewness") %>% mutate(stage = st)
  )
})

pred_list <- pred_list %>%
  mutate(
    stage = factor(stage, levels = stage_size_columns),
    response = factor(response, levels = c("Mean", "CV", "Skewness"))
  )



################################################################################
# 5) extract the parameter from the gam model
################################################################################

library(dplyr)
library(purrr)
library(tibble)

extract_gam_summary <- function(model, stage_name, response_name) {
  sm <- summary(model)
  
  # Parametric terms
  ptab <- as.data.frame(sm$p.table)
  if (nrow(ptab) > 0) {
    ptab$term <- rownames(ptab)
    rownames(ptab) <- NULL
    ptab <- ptab %>%
      transmute(
        stage = stage_name,
        response = response_name,
        term_type = "parametric",
        term = term,
        estimate = Estimate,
        std_error = `Std. Error`,
        t_value = `t value`,
        F = NA_real_,
        edf = NA_real_,
        ref_df = NA_real_,
        p_value = `Pr(>|t|)`
      )
  } else {
    ptab <- tibble()
  }
  
  # Smooth terms
  stab <- as.data.frame(sm$s.table)
  if (nrow(stab) > 0) {
    stab$term <- rownames(stab)
    rownames(stab) <- NULL
    
    # Handle possible column-name differences safely
    stab$edf    <- if ("edf" %in% names(stab)) stab[["edf"]] else NA_real_
    stab$ref_df <- if ("Ref.df" %in% names(stab)) stab[["Ref.df"]] else NA_real_
    stab$F      <- if ("F" %in% names(stab)) stab[["F"]] else NA_real_
    stab$p_value <- if ("p-value" %in% names(stab)) stab[["p-value"]] else NA_real_
    
    stab <- stab %>%
      transmute(
        stage = stage_name,
        response = response_name,
        term_type = "smooth",
        term = term,
        estimate = NA_real_,
        std_error = NA_real_,
        t_value = NA_real_,
        F = F,
        edf = edf,
        ref_df = ref_df,
        p_value = p_value
      )
  } else {
    stab <- tibble()
  }
  
  bind_rows(ptab, stab) %>%
    mutate(
      adj_r2 = sm$r.sq,
      dev_explained = sm$dev.expl,
      n = sm$n
    )
}

appendix_gam_table <- imap_dfr(stage_gam_list, function(stage_models, stage_name) {
  imap_dfr(stage_models, function(model, response_name) {
    if (is.null(model)) return(NULL)
    extract_gam_summary(model, stage_name, response_name)
  })
})

appendix_gam_table

write.csv(
  appendix_gam_table,
  "Results/Appendix_GAM_model_table.csv",
  row.names = FALSE
)

################################################################################
# 6) Plot the stage-specific body size metrics against relative density
################################################################################
#extract p
stage_pvalues <- imap_dfr(stage_gam_list, function(stage_models, stage_name) {
  
  imap_dfr(stage_models, function(model, metric_name) {
    
    sm <- summary(model)
    
    tibble(
      stage = stage_name,
      metric = metric_name,
      p = sm$s.table[1, "p-value"],
      F = sm$s.table[1, "F"],
      edf = sm$s.table[1, "edf"],
      dev_explained = sm$dev.expl
    )
    
  })
  
})

stage_pvalues$metric[which(stage_pvalues$metric=="Skew")]<-"Skewness"

stage_pvalues <- stage_pvalues %>%
  mutate(
    stage = factor(stage, levels = rev(stages)),
    metric = factor(metric,
                    levels = c("Mean", "CV", "Skewness"))
  )


#convert to significance
stage_pvalues <- stage_pvalues %>%
  mutate(
    sig = case_when(
      p < 0.001 ~ "***",
      p < 0.01  ~ "**",
      p < 0.05  ~ "*",
      TRUE      ~ ""
    )
  )


get_stage_label_map <- function(metric_name) {
  stage_pvalues %>%
    filter(metric == metric_name) %>%
    mutate(stage_lab = paste0(as.character(stage), " ", sig)) %>%
    distinct(stage, stage_lab) %>%
    tibble::deframe()
}

plot_stage_metric <- function(metric_name, response_col, ylab) {
  
  stage_label_map <- get_stage_label_map(metric_name)
  
  plot_df <- stage_summary %>%
    filter(is.finite(.data[[response_col]]))
  
  pred_df <- pred_list %>%
    filter(response == metric_name)
  
  ggplot(plot_df, aes(x = q, y = .data[[response_col]])) +
    geom_point(aes(colour = tube),alpha = 0.25, size = 0.8) +
    geom_ribbon(
      data = pred_df,
      aes(x = q, ymin = lwr, ymax = upr),
      inherit.aes = FALSE,
      fill = "grey70",
      alpha = 0.3
    ) +
    geom_line(
      data = pred_df,
      aes(x = q, y = fit),
      inherit.aes = FALSE,
      colour = "black",
      linewidth = 0.9
    ) +
    facet_wrap(
      ~ stage,
      scales = "free_y",
      ncol = 4,
      labeller = as_labeller(stage_label_map)
    ) +
    labs(
      x = "Relative density (N/K)",
      y = ylab,
      color = "Tube"
    ) +
    theme_classic()
}

p_mean <- plot_stage_metric("Mean", "mean_size", "Mean body size")
p_cv   <- plot_stage_metric("CV", "cv_size", "CV of body size")
p_skew <- plot_stage_metric("Skewness", "skew_size", "Skewness of body size")


ggsave(paste("Results/stage-specific response of mean body size to density.tif", sep = ""), 
       p_mean, width = 7, height = 4, dpi = 600, compression = "lzw")

ggsave(paste("Results/stage-specific response of CV of body size to density.tif", sep = ""), 
       p_cv, width = 7, height = 4, dpi = 600, compression = "lzw")

ggsave(paste("Results/stage-specific response of skewness of body size to density.tif", sep = ""), 
       p_skew, width = 7, height = 4, dpi = 600, compression = "lzw")





#########################EXTRA CODE############################################
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
abundance_focus <- c("nototal")
stages_group1 <- c("F", "FM", "SM","Qtritos", "Qprotos", "Qlarvae",
                "tritos", "deutos")
stage_group2<- c("protos","larvae","eggs")


library(lme4)
library(lmerTest)  # Optional: adds p-values to lmer

bootstrap_nls_ci <- function(model_object, data, predictor, response, B = 500, grid_n = 100) {
  library(minpack.lm)
  library(dplyr)
  
  model_formula <- formula(model_object)
  start_vals <- as.list(coef(model_object))
  
  # Build prediction grid
  
  pred_grid <- data.frame(seq(
    min(data[[predictor]], na.rm = TRUE),
    max(data[[predictor]], na.rm = TRUE),
    length.out = grid_n
  ))
  names(pred_grid) <- predictor
  
  preds <- matrix(NA, nrow = B, ncol = nrow(pred_grid))
  
  for (i in seq_len(B)) {
    sample_data <- data %>%
      dplyr::ungroup() %>%
      dplyr::slice_sample(n = nrow(.), replace = TRUE)
    
    fit <- try(nlsLM(model_formula, data = sample_data, start = start_vals, control = nls.lm.control(maxiter = 500)), silent = TRUE)
    
    if (!inherits(fit, "try-error")) {
      preds[i, ] <- predict(fit, newdata = pred_grid)
    }
  }
  
  # Fitted values from the original model
  pred_grid$fit <- predict(model_object, newdata = pred_grid)
  pred_grid$lwr <- apply(preds, 2, function(x) quantile(x, 0.025, na.rm = TRUE))
  pred_grid$upr <- apply(preds, 2, function(x) quantile(x, 0.975, na.rm = TRUE))
  
  return(pred_grid)
}

ribbon_cal<-function (mdl) {
  best_model<-get(mdl)
  if (mdl == "best_model_mean") {
    dataset <- summary_StaTest_scaled_clean
  } else {
    dataset <- summary_StaTest_clean
  }
  if (inherits(best_model, "lm") && length(coef(best_model)) == 1) {
    ci <- confint(best_model)  # Default is 95% CI
    ci_lower <- ci[1, 1]
    ci_upper <- ci[1, 2]
    intercept <<- coef(best_model)[1]
    # Create a dummy x range for the ribbon
    x_range <- range(dataset$nototal, na.rm = TRUE)
    ribbon_df <- data.frame(
      nototal = x_range,
      lwr = ci_lower,
      upr = ci_upper
    )
  }
  else if (inherits(best_model, "lm") && length(coef(best_model)) > 1) {
    ribbon_df <- data.frame(nototal = seq(min(dataset[["nototal"]], na.rm = TRUE),
                                          max(dataset[["nototal"]], na.rm = TRUE),
                                          length.out = 100))
    fit <- predict(best_model, newdata = ribbon_df, interval = "confidence")
    ribbon_df <- cbind(ribbon_df, fit)
  } else {
    ribbon_df <- bootstrap_nls_ci(
      model_object = best_model,
      data = dataset,
      predictor = "nototal",
      response = ifelse(mdl=="best_model_mean",  "mean_size","CV_size"),
      B = 500,
      grid_n = 100
    )}
  return(ribbon_df)
} 

plot_list_mean <- list()
plot_list_CV <- list()
for (stg in (c(stages_group1, stage_group2))) {
  print(stg)
  #calculate mean and standard deviation of body size at stage group:stg
    summary_StaTest <- merged_data %>%
      group_by(day, tube, Equ, nototal) %>%
      summarize(
        CV_size   = ifelse(all(is.na(.data[[stg]])), NA, sd(.data[[stg]], na.rm = TRUE)/ 
                             mean(.data[[stg]], na.rm = TRUE))
      )
    
    summary_StaTest_scaled <- merged_data_scaled %>%
      group_by(day, tube, Equ, nototal) %>%
      summarize(
        mean_size = ifelse(all(is.na(.data[[stg]])), NA, mean(.data[[stg]], na.rm = TRUE)),
      )
    
    
    summary_StaTest_clean <- summary_StaTest %>%
      filter(!is.na(CV_size))
    summary_StaTest_scaled_clean <- summary_StaTest_scaled %>%
      filter(!is.na(mean_size))
    
    summary_StaTest_clean$Equ<-factor(summary_StaTest_clean$Equ, 
                                         levels=c("Less than half K",
                                                  "Half K to K",
                                                  "Equilibrium"))
    summary_StaTest_scaled_clean$Equ<-factor(summary_StaTest_scaled_clean$Equ, 
                                         levels=c("Less than half K",
                                                  "Half K to K",
                                                  "Equilibrium"))
    #null model
    print("null_model_mean")
    null_model_mean <- lm(mean_size ~ 1, data = summary_StaTest_scaled_clean)
    print("null_model_CV")
    null_model_CV <- lm(CV_size ~ 1, data = summary_StaTest_clean)
    
    
    # Linear model
    print("linear_model_mean")
    linear_model_mean <- lm(mean_size ~ nototal, data = summary_StaTest_scaled_clean)
    print("linear_model_CV")
    linear_model_CV <- lm(CV_size ~ nototal, data = summary_StaTest_clean)
    
    #polynomial) model
    print("poly2_model_mean")
    poly2_model_mean <- lm(mean_size ~ poly(nototal, 2), data = summary_StaTest_scaled_clean)
    print("poly2_model_CV")
    poly2_model_CV <- lm(CV_size ~ poly(nototal, 2), data = summary_StaTest_clean)
    
    print("poly3_model_mean")
    poly3_model_mean <- lm(mean_size ~ poly(nototal, 3), data = summary_StaTest_scaled_clean)
    print("poly3_model_CV")
    poly3_model_CV <- lm(CV_size ~ poly(nototal, 3), data = summary_StaTest_clean)

    #Logistic model
    print("logistic_model_mean")
    k_flex<-ifelse(stg=="larvae"|stg=="protos", -0.000001, -0.01)
    logistic_model_mean <- nlsLM(
      mean_size ~ A / (1 + exp(-k * (nototal - x0))) + C,
      data = summary_StaTest_scaled_clean,
      start = list(A = 0.3, k = k_flex, x0 = 150, C = 0.3),
      control = nls.lm.control(maxiter = 500)
    )
    print("logistic_model_CV")
    k_flex<-ifelse(stg=="deutos"|stg=="Qlarvae", 0, -0.01)
    logistic_model_CV <- nlsLM(
      CV_size ~ A / (1 + exp(-k * (nototal - x0)))+C  ,
      data = summary_StaTest_clean,
      start = list(A = 0.1, k = k_flex, x0 =0, C = 0),
      control = nls.lm.control(maxiter = 500)
    )
    
    #Gaussian model
    print("gaussian_model_mean")
    gaussian_model_mean <- nlsLM(
      mean_size ~ a * exp(-((nototal - x0)^2) / (2 * sigma^2))+C,
      data = summary_StaTest_scaled_clean,
      start = list(a = 0.6, x0 = 150, sigma = 50, C=0.3),
      control = nls.lm.control(maxiter = 500)
    )
    print("gaussian_model_CV")
    gaussian_model_CV <- nlsLM(
      CV_size ~ a * exp(-((nototal - x0)^2) / (2 * sigma^2)),
      data = summary_StaTest_clean,
      start = list(a = 0.6, x0 = 150, sigma = 50),
      control = nls.lm.control(maxiter = 500)
    )
    
    # Compare models
    aic_table_mean <- AIC(null_model_mean, linear_model_mean, poly2_model_mean, poly3_model_mean, 
                          logistic_model_mean, gaussian_model_mean)
    aic_table_CV <- AIC(null_model_CV, linear_model_CV, poly2_model_CV, poly3_model_CV, 
                        logistic_model_CV, gaussian_model_CV)
    
    # Print the table (optional)
    print(aic_table_mean)
    print(aic_table_CV)
    # Find model with the lowest AIC
    best_model_name_mean <- rownames(aic_table_mean)[which.min(aic_table_mean$AIC)]
    best_model_name_CV <- rownames(aic_table_CV)[which.min(aic_table_CV$AIC)]
    # Access the model object (if needed)
    best_model_mean <- get(best_model_name_mean)
    best_model_CV<-get(best_model_name_CV)
    
    #prepare the dataset to show AIC in the plot
    label_data_mean <- data.frame(
      x = rep(650, 7),
      y = seq(1,0.5, length.out = 7),  # space them out top-down
      label = c("AIC", round(aic_table_mean$AIC, 2))
    )
    
    label_data_CV <- data.frame(
      x = rep(650, 7),
      y = seq(0.4,0.2, length.out = 7),  # space them out top-down
      label = c("AIC", round(aic_table_CV$AIC, 2))
    )
    

    
    #MEAN_detect where the best regression model is linear or non-linear and prepare dataset for ribbon
  ribbon_df<-ribbon_cal("best_model_mean")
    # Create base plot of mean
  mean_size_vs_nototal <-
        ggplot(summary_StaTest_scaled_clean, aes(x = nototal, y = mean_size, color = Equ)) +
        geom_point(alpha = 0.6) +
        geom_ribbon(data = ribbon_df, aes(x = nototal, ymin = lwr, ymax = upr), 
                    inherit.aes = FALSE, fill = "black", alpha = 0.2) +
        geom_text(data = label_data_mean, aes(x = x, y = y, label = label),
                  inherit.aes = FALSE, hjust = 0, size = 2)+
        xlim(0,800) +
        ylim(0,1)+
        theme_minimal()+
        labs(
          title = stg,
          x = ifelse(stg=="deutos"|stg=="protos"|stg=="larvae"|stg=="eggs", 
                     "Population size", ""),
          y = ifelse(stg=="F"|stg=="Qtritos"|stg=="tritos"|stg=="larvae", 
                     "Mean body size", ""),
          color = "Population Stage"
        )+
          theme(
            legend.position = ifelse(stg=="SM","right", "none") 
          )
  
  ## Conditionally add line for mean plot
  if (inherits(best_model_mean, "lm") && length(coef(best_model_mean)) == 1) {
    mean_size_vs_nototal <- mean_size_vs_nototal+
    geom_hline(yintercept = intercept, color = "black", size = 1)
    
  } else {
  mean_size_vs_nototal <- mean_size_vs_nototal +  
    geom_line(data=ribbon_df, aes(x = nototal, y = fit), color = "black", size = 1)
  }
  
  ribbon_df<-ribbon_cal("best_model_CV") 
  # Create base plot of mean
    CV_size_vs_nototal <-
      ggplot(summary_StaTest_clean, aes(x = nototal, y = CV_size, color = Equ)) +
      geom_point(alpha = 0.6) +
      geom_ribbon(data = ribbon_df, aes(x = nototal, ymin = lwr, ymax = upr), 
                  inherit.aes = FALSE, fill = "black", alpha = 0.2) +
      geom_text(data = label_data_CV, aes(x = x, y = y, label = label),
                inherit.aes = FALSE, hjust = 0, size = 2)+
      xlim(0,800) +
      ylim(0,0.4)+
      theme_minimal() +
      labs(
        title = stg,
        x = ifelse(stg=="deutos"|stg=="protos"|stg=="larvae"|stg=="eggs", 
                   "Population size", ""),
        y = ifelse(stg=="F"|stg=="Qtritos"|stg=="tritos"|stg=="larvae", 
                   "CV of body size", ""),
        color = "Population Stage"
      ) +
      theme(
        legend.position = ifelse(stg=="SM","right", "none")
      )
    
    ## Conditionally add line for mean plot
    if (inherits(best_model_CV, "lm") && length(coef(best_model_CV)) == 1) {
      CV_size_vs_nototal <- CV_size_vs_nototal+
        geom_hline(yintercept = intercept, color = "black", size = 1)
      
    } else {
      CV_size_vs_nototal <- CV_size_vs_nototal +  
        geom_line(data=ribbon_df, aes(x = nototal, y = fit), color = "black", size = 1)
    }
    
    plot_list_mean[[stg]] <- mean_size_vs_nototal
    plot_list_CV[[stg]] <-CV_size_vs_nototal
}

top_row_mean <- plot_list_mean[["F"]] | plot_list_mean[["FM"]]|plot_list_mean[["SM"]]
mid_up_row_mean <-plot_list_mean[["Qtritos"]] | plot_list_mean[["Qprotos"]]|
  plot_list_mean[[ "Qlarvae"]]
mid_bottom_row_mean <-plot_list_mean[["tritos"]]|plot_list_mean[["deutos"]]|
  plot_list_mean[["protos"]] 
bottom_row_mean<-  plot_list_mean[["larvae"]]|plot_list_mean[[ "eggs"]]

top_row_CV <- plot_list_CV[["F"]] | plot_list_CV[["FM"]]|plot_list_CV[["SM"]]
mid_up_row_CV <-plot_list_CV[["Qtritos"]] | plot_list_CV[["Qprotos"]]|
  plot_list_CV[[ "Qlarvae"]]
mid_bottom_row_CV <-plot_list_CV[["tritos"]]|plot_list_CV[["deutos"]]|
  plot_list_CV[["protos"]] 
bottom_row_CV<-  plot_list_CV[["larvae"]]|plot_list_CV[[ "eggs"]]


# Combine plots for adults
final_plot_mean <- top_row_mean /
  mid_up_row_mean /
  mid_bottom_row_mean /
  bottom_row_mean +
  plot_layout(heights = c(1, 1, 1, 1)) +   # 4 heights
  plot_annotation(tag_levels = 'a')
final_plot_mean

final_plot_CV <- top_row_CV /
  mid_up_row_CV /
  mid_bottom_row_CV /
  bottom_row_CV +
  plot_layout(heights = c(1, 1, 1, 1)) +   # 4 heights
  plot_annotation(tag_levels = 'a')
final_plot_CV


#Save
ggsave(paste("Results/mean body size vs population size.tiff", sep = ""), 
       final_plot_mean, width = 8, height = 9, dpi = 600, compression = "lzw")

ggsave(paste("Results/CV of body size  vs population size.tiff", sep = ""), 
       final_plot_CV, width = 8, height = 9, dpi = 600, compression = "lzw")



